// components/DoctorLetter.tsx
"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Download, Loader2, Copy, Check, Printer, X } from "lucide-react";
import toast from "react-hot-toast";

interface Test {
    test: string;
    value: number;
    unit: string;
    range: string;
    flag: "normal" | "high" | "low";
    advice?: string;
}

interface DoctorLetterProps {
    reportData: {
        fileName?: string;
        summary?: string;
        recommendation?: string;
        overallScore?: number;
        riskLevel?: string;
        tests?: Test[];
        supplements?: { name: string; dose?: string; reason: string }[];
        futurePredictions?: { condition: string; risk: string; prevention: string }[];
        medicationAlerts?: { medication: string; marker: string; interaction: string; suggestion: string }[];
    };
    patientName?: string;
}

function generateLetter(reportData: DoctorLetterProps["reportData"], patientName: string): string {
    const today = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
    const abnormal = (reportData.tests || []).filter(t => t.flag !== "normal");

    const testRows = (reportData.tests || []).map(t =>
        `  • ${t.test}: ${t.value} ${t.unit} (Reference: ${t.range}) — ${t.flag.toUpperCase()}`
    ).join("\n");

    const concernsText = abnormal.length > 0
        ? `\nNOTABLE CONCERNS:\n${abnormal.map(t => `  • ${t.test} is ${t.flag} at ${t.value} ${t.unit} (normal: ${t.range}). ${t.advice || ""}`).join("\n")}`
        : "";

    const predictionsText = (reportData.futurePredictions || []).length > 0
        ? `\nFUTURE RISK CONSIDERATIONS:\n${reportData.futurePredictions!.map(p =>
            `  • ${p.condition} (Risk: ${p.risk}) — ${p.prevention}`
        ).join("\n")}`
        : "";

    const medsText = (reportData.medicationAlerts || []).length > 0
        ? `\nMEDICATION INTERACTION NOTES:\n${reportData.medicationAlerts!.map(m =>
            `  • ${m.medication} ↔ ${m.marker}: ${m.interaction}. Suggestion: ${m.suggestion}`
        ).join("\n")}`
        : "";

    const supplementsText = (reportData.supplements || []).length > 0
        ? `\nRECOMMENDED SUPPLEMENTS (Please Review):\n${reportData.supplements!.map(s =>
            `  • ${s.name} ${s.dose || ""} — ${s.reason}`
        ).join("\n")}`
        : "";

    return `BLOOD REPORT SUMMARY LETTER
For: ${patientName || "Patient"}
Date: ${today}
Report: ${reportData.fileName || "Blood Analysis Report"}
Overall Health Score: ${reportData.overallScore ?? "N/A"}/10 | Risk Level: ${(reportData.riskLevel || "unknown").toUpperCase()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Dear Doctor,

I am writing to share the results of my recent blood report for your review. The following AI-assisted analysis was generated for informational purposes and is not a substitute for professional medical evaluation.

SUMMARY:
${reportData.summary || "See attached report."}

KEY RECOMMENDATION:
${reportData.recommendation || "See report for details."}

ALL TEST RESULTS:
${testRows || "  No tests extracted."}
${concernsText}
${predictionsText}
${medsText}
${supplementsText}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

I would appreciate your professional assessment of these results and guidance on next steps, particularly regarding the ${abnormal.length > 0 ? abnormal.map(t => t.test).join(", ") : "results above"}.

Thank you for your time and expertise.

Sincerely,
${patientName || "Patient"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Note: This letter was auto-generated by BloodReport AI for patient convenience.
This is NOT a medical diagnosis. Always follow your doctor's advice.`;
}

export default function DoctorLetter({ reportData, patientName = "" }: DoctorLetterProps) {
    const [isOpen, setIsOpen] = useState(false);
    const [name, setName] = useState(patientName);
    const [copied, setCopied] = useState(false);

    const letter = generateLetter(reportData, name);

    const handleCopy = () => {
        navigator.clipboard.writeText(letter);
        setCopied(true);
        toast.success("Letter copied to clipboard!");
        setTimeout(() => setCopied(false), 2500);
    };

    const handleDownload = () => {
        const blob = new Blob([letter], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `Doctor_Letter_${new Date().toISOString().split("T")[0]}.txt`;
        a.click();
        URL.revokeObjectURL(url);
        toast.success("Letter downloaded!");
    };

    const handlePrint = () => {
        const printWin = window.open("", "_blank");
        if (!printWin) return;
        printWin.document.write(`<html><head><title>Doctor Letter</title><style>
      body { font-family: 'Courier New', monospace; font-size: 13px; line-height: 1.7; margin: 40px; color: #111; white-space: pre-wrap; }
    </style></head><body>${letter.replace(/\n/g, "<br>")}</body></html>`);
        printWin.document.close();
        printWin.print();
    };

    return (
        <>
            <motion.button
                whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}
                onClick={() => setIsOpen(true)}
                className="flex items-center gap-2 px-5 py-3 rounded-2xl bg-secondary-500/15 border border-secondary-500/25 text-secondary-300 hover:bg-secondary-500/25 transition-all text-sm font-semibold">
                <FileText className="w-4 h-4" />
                Doctor Letter
            </motion.button>

            <AnimatePresence>
                {isOpen && (
                    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4">
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                            onClick={() => setIsOpen(false)}
                            className="absolute inset-0 bg-black/70 backdrop-blur-md" />

                        <motion.div
                            initial={{ scale: 0.92, opacity: 0, y: 20 }}
                            animate={{ scale: 1, opacity: 1, y: 0 }}
                            exit={{ scale: 0.92, opacity: 0, y: 20 }}
                            onClick={e => e.stopPropagation()}
                            className="relative w-full max-w-2xl max-h-[90vh] flex flex-col rounded-3xl overflow-hidden shadow-2xl"
                            style={{ background: "#0f0520", border: "1px solid rgba(124,58,237,0.2)" }}>

                            <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-secondary-500 to-transparent" />

                            {/* Header */}
                            <div className="flex items-center justify-between p-6 border-b border-white/8 shrink-0">
                                <div>
                                    <h2 className="text-xl font-bold text-white flex items-center gap-2.5">
                                        <FileText className="w-5 h-5 text-secondary-400" /> Doctor Summary Letter
                                    </h2>
                                    <p className="text-gray-500 text-xs mt-1">A formatted letter you can share with your physician</p>
                                </div>
                                <button onClick={() => setIsOpen(false)}
                                    className="p-2 rounded-xl bg-white/5 hover:bg-white/10 text-gray-500 hover:text-white transition-all">
                                    <X className="w-4 h-4" />
                                </button>
                            </div>

                            {/* Name input */}
                            <div className="px-6 py-4 border-b border-white/8 shrink-0">
                                <label className="text-xs text-gray-500 font-medium mb-1.5 block">Your name (for the letter)</label>
                                <input type="text" value={name} onChange={e => setName(e.target.value)}
                                    placeholder="e.g. Rahul Sharma"
                                    className="w-full max-w-xs bg-white/5 border border-white/10 text-white placeholder:text-gray-600 px-4 py-2.5 rounded-xl focus:outline-none focus:border-secondary-500/50 text-sm" />
                            </div>

                            {/* Letter preview */}
                            <div className="flex-1 overflow-y-auto p-6">
                                <pre className="text-gray-300 text-xs leading-relaxed whitespace-pre-wrap font-mono bg-white/3 border border-white/6 rounded-2xl p-5">
                                    {letter}
                                </pre>
                            </div>

                            {/* Actions */}
                            <div className="flex flex-wrap gap-3 p-6 border-t border-white/8 shrink-0">
                                <button onClick={handleCopy}
                                    className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/8 border border-white/10 text-gray-300 hover:text-white hover:bg-white/12 transition-all text-sm font-medium">
                                    {copied ? <Check className="w-4 h-4 text-accent-400" /> : <Copy className="w-4 h-4" />}
                                    {copied ? "Copied!" : "Copy"}
                                </button>
                                <button onClick={handlePrint}
                                    className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/8 border border-white/10 text-gray-300 hover:text-white hover:bg-white/12 transition-all text-sm font-medium">
                                    <Printer className="w-4 h-4" /> Print
                                </button>
                                <button onClick={handleDownload}
                                    className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-secondary-600 to-secondary-500 text-white shadow-lg shadow-secondary-600/25 hover:shadow-secondary-500/40 transition-all text-sm font-bold ml-auto">
                                    <Download className="w-4 h-4" /> Download .txt
                                </button>
                            </div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>
        </>
    );
}
